openapi: 3.0.3
info:
  title: OpenAPI schema for Ingress NGINX template .
components:
  schemas:
    variables:
      type: object
      properties:
        helm_release_name:
          title: Helm Release Name
          type: string
          description: The name of the Helm release.
          default: ingress-nginx
          x-walrus-ui:
            group: Basic
            order: 1
        namespace_name:
          title: Namespace Name
          type: string
          description: The namespace where the Helm release will be installed.
          default: kube-system
          x-walrus-ui:
            group: Basic
            order: 2
        helm_chart_version:
          title: Helm Chart Version
          type: string
          description: The version of the ingress-nginx Helm chart.
          default: 4.11.3
          x-walrus-ui:
            group: Basic
            order: 3
        metrics:
          title: Metrics
          type: boolean
          description: Enabled Metrics in the ingress-nginx Helm chart.
          default: "true"
          x-walrus-ui:
            group: Basic
            order: 4
        resources:
          title: Resources
          type: object
          description: Resource limits and requests for the Ingress NGINX Helm release.
          default:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          additionalProperties:
            additionalProperties:
              type: string
            type: object
            x-walrus-ui:
              colSpan: 12
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 5
        values:
          title: Values
          type: object
          description: Chart values
          default: {}
          x-walrus-ui:
            colSpan: 12
            group: Basic
            order: 6
            widget: YamlEditor
      x-walrus-ui:
        groupOrder:
        - Basic
