controller:
  metrics:
    service:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "10254"
  allowSnippetAnnotations: true
  config:
    use-forwarded-headers: "true"
    allowSnippetAnnotations: "true"